// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcS4b5CXG2p9YA3nmyY6btFvtG-gaFLR4',
    appId: '1:200125169386:web:6ea5f648bae0d70acb2193',
    messagingSenderId: '200125169386',
    projectId: 'office-fbdb',
    authDomain: 'office-fbdb.firebaseapp.com',
    storageBucket: 'office-fbdb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9q_KEyg-WxFKPc6MchEFx55M_vW4k7Dk',
    appId: '1:200125169386:android:cb984fce5a3bd56ecb2193',
    messagingSenderId: '200125169386',
    projectId: 'office-fbdb',
    storageBucket: 'office-fbdb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2J0A9d9Y4Yq1XXAskqfjWgvrPT9QzDuM',
    appId: '1:200125169386:ios:448e50ba752ae46acb2193',
    messagingSenderId: '200125169386',
    projectId: 'office-fbdb',
    storageBucket: 'office-fbdb.firebasestorage.app',
    iosBundleId: 'com.example.demoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2J0A9d9Y4Yq1XXAskqfjWgvrPT9QzDuM',
    appId: '1:200125169386:ios:eb3fa8f4d022d895cb2193',
    messagingSenderId: '200125169386',
    projectId: 'office-fbdb',
    storageBucket: 'office-fbdb.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcS4b5CXG2p9YA3nmyY6btFvtG-gaFLR4',
    appId: '1:200125169386:web:150d7eda672925cfcb2193',
    messagingSenderId: '200125169386',
    projectId: 'office-fbdb',
    authDomain: 'office-fbdb.firebaseapp.com',
    storageBucket: 'office-fbdb.firebasestorage.app',
  );
}
